### ISSUE TITLE
jest specs complain about "Invalid prop 'svg'"

### ISSUE THREAD

**Issue by ajwann** [ajwann/svg-loaders-react#23]
The [CI server](https://travis-ci.org/ajwann/svg-loaders-react) is passing, but each spec is logging a warning about an invalid prop type. This appears to be a problem with the test suite set-up, and not a poroblem with the actual
props being passed. 

The error is
```
Warning: Failed prop type: Invalid prop `svg` of type `object` supplied to `SVGInline`, expected `string`.
          in SVGInline
```

[Based on this issue from enzyme](https://github.com/airbnb/enzyme/issues/889)
it looks like the issue can be fixed by adding the following moduleNameMapper to the
jest.config.js file:
```
moduleNameMapper: { 
  '\\.svg$': '<rootDir>/assets/mocks/svgMock.js', 
} 
```

**Comment by pandasa123** [comment]
Alrighty so there are a few options. It is the actual props being passed in that's causing the issue: `SVGInline` is complaining is because it's expecting a string rather than an object. 

We could:
1. `<SVGInline svg={toString(image)} {...props} />`
2. `<SVGInline svg={`Actual SVG markup etc`} {...props} />`

Both are quick. I'd recommend the second one since this is a static library and we'd get rid of the svg files themselves etc

**Comment by ajwann** [comment]
Ah bummer, I was hoping it was just an issue with the specs. I definitely don't think your proposed solutions are wrong, but since the react-svg-inline library is deprecated, I'd like to get rid of it as a dependency. Take a look at my comment on your PR.

**Comment by pandasa123** [comment]
Fixed everything up. `index.js` is considerably smaller + removed unused dependencies etc
